#!/bin/sh

VIRTUAL_ENV="FPGA Env"

_OLD_ENVIRONMENT_PS1="${PS1-}"
if [ -n "${ZSH_VERSION-}" ] ; then
    autoload -U colors && colors
    PS1="%{$fg[magenta]%}(${VIRTUAL_ENV})%{$reset_color%} ${PS1-}"
else
    PS1="\[\033[1;35m\]\342\246\227${VIRTUAL_ENV}\342\246\230\[\033[0m\] ${PS1-}"
fi
export PS1

# create alias for yosys to include ghdl
alias yosys='yosys -m ghdl'

export PATH=~/sft/bin:$PATH
